/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131315",
        surface: "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f22",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c6c5d5",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        outline: "#908f9e",
        "outline-variant": "#454653",
        "surface-tint": "#bdc2ff",
        primary: "#bdc2ff",
        "on-primary": "#131e8c",
        "primary-container": "#818cf8",
        "on-primary-container": "#101b8a",
        "inverse-primary": "#4953bc",
        secondary: "#ddb8ff",
        "on-secondary": "#490081",
        "secondary-container": "#62259b",
        "on-secondary-container": "#d1a1ff",
        tertiary: "#3cddc7",
        "on-tertiary": "#003731",
        "tertiary-container": "#00a896",
        "on-tertiary-container": "#00352e",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e0e0ff",
        "primary-fixed-dim": "#bdc2ff",
        "on-primary-fixed": "#000767",
        "on-primary-fixed-variant": "#2f3aa3",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#ddb8ff",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#62259b",
        "tertiary-fixed": "#62fae3",
        "tertiary-fixed-dim": "#3cddc7",
        "on-tertiary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#005047",
        "on-background": "#e5e1e4",
        "surface-variant": "#353437",
      },
      fontFamily: {
        manrope: ["var(--font-manrope)", "sans-serif"],
        inter: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        base: "4px",
        "container-padding": "32px",
        gutter: "24px",
        "card-gap": "16px",
        "section-margin": "48px",
      },
    },
  },
  plugins: [],
}
